export const ADDLISTITEM_REQUEST = 'ADDLISTITEM_REQUEST';

export const ADD_NEW_LIST_ITEM = 'ADD_NEW_LIST_ITEM';

export const FETCH_USER_LISTS = 'FETCH_USER_LISTS';
export const UPDATE_USER_INPUT_CATEGORY = 'UPDATE_USER_INPUT_CATEGORY';

export const UPDATE_LISTS_STATE = 'UPDATE_LISTS_STATE';

export const UPDATE_SINGLE_LIST_STATE = 'UPDATE_SINGLE_LIST_STATE';

export const USER_TYPE_START = 'USER_TYPE_START';

export const USER_CATEGORY_SELECTED = 'USER_CATEGORY_SELECTED';

export const UPDATE_FILTER_STATE = 'UPDATE_FILTER_STATE';
