// ******* ADD ITEM SECTION ******
export const USER_TYPE_START = 'USER_TYPE_START';
export const UPDATE_USER_INPUT_CATEGORY = 'UPDATE_USER_INPUT_CATEGORY';
export const ADD_NEW_LIST_ITEM = 'ADD_NEW_LIST_ITEM';
export const TOGGLE_SHOW = 'TOGGLE_SHOW';
export const TOGGLE = 'TOGGLE';

// ******* ADD ITEM SECTION ****** REFACTORED
export const ADD_ITEM_LOCALLY = 'ADD_ITEM_LOCALLY';
export const CLEAR_INPUT_AFTER_SUBMIT = 'CLEAR_INPUT_AFTER_SUBMIT';
export const TOGGLE_CHECK = 'TOGGLE_CHECK';

// server/database interactions
export const ADD_NEW_LIST_ITEM_DATABASE_REQUEST = 'ADD_NEW_LIST_ITEM_DATABASE_REQUEST';
export const ADD_NEW_LIST_ITEM_DATABASE_FAILURE = 'ADD_NEW_LIST_ITEM_DATABASE_FAILURE';
export const ADD_NEW_LIST_ITEM_DATABASE_SUCCESS = 'ADD_NEW_LIST_ITEM_DATABASE_SUCCESS';
// ******* EDIT ITEMS SECTION ******
export const DELETE_LIST_ITEM_DATABASE_REQUEST = 'DELETE_LIST_ITEM_DATABASE_REQUEST';
export const DELETE_LIST_ITEM_DATABASE_FAILURE = 'DELETE_LIST_ITEM_DATABASE_FAILURE';
export const DELETE_LIST_ITEM_DATABASE_SUCCESS = 'DELETE_LIST_ITEM_DATABASE_SUCCESS';
export const DELETE_CONFIRM_ON = 'DELETE_CONFIRM_ON';
export const DELETE_CONFIRM_OFF = 'DELETE_CONFIRM_OFF';

// ******* TOGGLE ITEMS SECTION ******
export const TOGGLE_ITEM_REQUEST = "TOGGLE_ITEM_REQUEST";
export const TOGGLE_ITEM_SUCCESS = "TOGGLE_ITEM_SUCCESS";
export const TOGGLE_ITEM_FAILURE = "TOGGLE_ITEM_FAILURE";

// ******* FETCH ITEMS SECTION ******
export const UPDATE_LISTS_CATEGORY = 'UPDATE_LISTS_CATEGORY';
export const UPDATE_ALL_LISTS_STATE = 'UPDATE_ALL_LISTS_STATE';
export const UPDATE_SINGLE_LIST_STATE = 'UPDATE_SINGLE_LIST_STATE';
export const UPDATE_FILTER_STATE = 'UPDATE_FILTER_STATE';

export const FETCH_DATABASE_LISTS_REQUEST = 'FETCH_DATABASE_LISTS_REQUEST';
export const FETCH_DATABASE_LISTS_FAILURE = 'FETCH_DATABASE_LISTS_FAILURE';
export const FETCH_DATABASE_LISTS_SUCCESS = 'FETCH_DATABASE_LISTS_SUCCESS';

// ******* LOGIN SECTION ******
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const RESET_UI_DISPLAY = "RESET_UI_DISPLAY";
export const AUTHORIZE_REQUEST = "AUTHORIZE_REQUEST";
export const AUTHORIZE_SUCCESS = "AUTHORIZE_SUCCESS";
export const AUTHORIZE_FAILURE = "AUTHORIZE_FAILURE";
// export const AUTHORIZING_USER = "AUTHORIZING_USER";

// ******* LIST SCREEN SECTION ******
export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";

// Where is this being called??
export const FETCH_USER_LISTS = 'FETCH_USER_LISTS';

// ******* LIST SCREEN SECTION ******
export const DATE_CHANGE = "DATE_CHANGE";

// ******* FOLLOW SCREEN SECTION ******
export const SELECT_SEARCH = "SELECT_SEARCH";
export const SELECT_FOLLOWERS = "SELECT_FOLLOWERS";
export const SELECT_FOLLOWINGS = "SELECT_FOLLOWINGS";


// ******* AUTOCOMPLETE SECTION ******
export const UPDATE_SEARCH_SUGGESTIONS = 'UPDATE_SEARCH_SUGGESTIONS';
export const UPDATE_SEARCH_SUGGESTIONS_SUCCESS = 'UPDATE_SEARCH_SUGGESTIONS_SUCCESS';
export const UPDATE_USER_INPUT = 'UPDATE_USER_INPUT';
export const CLEAR_SUGGESTION = 'CLEAR_SUGGESTION';
